blog/urls.py
from django.urls import path
from .views import PostListView
from . import views


app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='news'),
]

egichem/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


admin.site.site_header = "EgiChem Admin"
admin.site.site_title = "EgiChem Admin Portal"
# admin.site.index_title = "Welcome to EgiChem Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('website.urls')),
    path('news/', include('blog.urls')),
    path('contact/', include('sendemail.urls')),
    path('my-egichem/', include('lab.urls')),
    path('tools/calculators/', include('calculators.urls')),
]

# Used to serve media files locally
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab/urls.py
from django.urls import path
from .views import MaterialListView, MaterialCreateView, MaterialDeleteView, MaterialUpdateView, AnnouncementListView, AnnouncementCreateView, FaqListView
from . import views


urlpatterns = [
    path('', views.egichem, name='egichem'),
    # path('inventory/', views.inventory, name='inventory'),
    path('inventory/', MaterialListView.as_view(), name='inventory'),
    path('inventory/material/new/', MaterialCreateView.as_view(), name='material-create'),
    path('inventory/material/<int:pk>/update/', MaterialUpdateView.as_view(), name='material-update'),
    path('inventory/material/<int:pk>/delete/', MaterialDeleteView.as_view(), name='material-delete'),
    path('inventory/export/', views.export, name='export'),
    path('announcements/', AnnouncementListView.as_view(), name='announcements'),
    path('announcements/new/', AnnouncementCreateView.as_view(), name='announcement-create'),
    path('announcements/<int:pk>/delete/', views.announcement_delete, name='announcement-delete'),
    path('lab-teams/', views.lab_teams, name='lab_teams'),
    path('faq/', FaqListView.as_view(), name='faqs'),
    path('contacts/', views.contacts, name='contacts'),
]

website/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('research/', views.research, name='research'),
    path('people/', views.people, name='people'),
    # path('lab/', views.lab, name='lab'),
    path('publications/', views.publications, name='publications'),
    path('partners/', views.partners, name='partners'),
    # path('news/', views.news, name='news'),  # handled via blog app
    path('tools/', views.tools, name='tools'),
    # path('contact/', views.contact, name='contact'),  # handled via sendemail app
    path('awards/', views.awards, name='awards'),
    path('people/<slug:name_slug>/', views.member_page, name='member_page'),
]

lab/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from website.models import Member
from datetime import datetime
import cirpy


class Material(models.Model):
    TYPES = (
        ('Reagent', 'Reagent'),
        ('Material', 'Material'),
        ('Tool', 'Tool'),
        ('Other', 'Other'),
    )
    item_type = models.CharField(max_length=50, choices=TYPES, default='Reagent')
    name = models.CharField(max_length=200)
    specifications = models.CharField(max_length=500, blank=True)
    cas = models.CharField(max_length=50, blank=True, verbose_name='CAS')
    amount = models.IntegerField(default=1, validators=[MaxValueValidator(1000), MinValueValidator(0)])
    location = models.CharField(max_length=500, blank=True)
    msds_url = models.URLField(blank=True, verbose_name='MSDS URL')
    comments = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,)

    class Meta:
        permissions = (
            ('manage_inventory', 'Can manage inventory'),
        )

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('inventory')

    def save(self, *args, **kwargs):
        # Add CAS number to database if it is a newly created object, so set CAS number
        if not self.cas:
            try:
                query = cirpy.resolve(self.name, 'cas')
                cas_result = query[0]
                for number in query:
                    if len(number) < len(cas_result):
                        cas_result = number
            
                self.cas = cas_result
            except:
                pass

        super(Material, self).save(*args, **kwargs)


class Announcement(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ('manage_inventory', 'Can manage inventory'),
        )

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('announcements')


class ExternalResource(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    resource_type = models.TextField(blank=True)
    url1 = models.URLField()
    url1_text = models.CharField(max_length=15, default='Link')
    url2 = models.URLField(blank=True)
    url2_text = models.CharField(max_length=15, default='Link2')
    url3 = models.URLField(blank=True)
    url3_text = models.CharField(max_length=15, default='Link3')
    date_added = models.DateTimeField(default=timezone.now)
    order = models.IntegerField(default=99)

    # class Meta:
    #     permissions = (
    #         ('manage_inventory', 'Can manage inventory'),
    #     )

    def __str__(self):
        return f'{self.title}'


class LabTeam(models.Model):
    class Month(models.IntegerChoices):
        JANUARY = 1
        FEBRUARY = 2
        MARCH = 3
        APRIL = 4
        MAY = 5
        JUNE = 6
        JULY = 7
        AUGUST = 8
        SEPTEMBER = 9
        OCTOBER = 10
        NOVEMBER = 11
        DECEMBER = 12

    month = models.IntegerField(choices=Month.choices, default=datetime.now().month)
    year = models.IntegerField(default=datetime.now().year)
    cleaning = models.ManyToManyField(Member, related_name='cleaning_team', limit_choices_to={'alumni': False}, blank=True)
    technic = models.ManyToManyField(Member, related_name='technic_team', limit_choices_to={'alumni': False}, blank=True)
    safety = models.ManyToManyField(Member, related_name='safety_team', limit_choices_to={'alumni': False}, blank=True)

    def __str__(self):
        return f'{self.year}/{self.month} Teams'


class Faq(models.Model):
    question = models.TextField()
    answer =models.TextField()
    order = models.IntegerField(default=99)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Q: {self.question}'

website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify


class MainResearchArea(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    order = models.IntegerField(default=99)

    def __str__(self):
        return self.title


class ResearchField(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(default='images/350x200.png', upload_to='images/research-fields')
    date_added = models.DateTimeField(default=timezone.now)
    order = models.IntegerField(default=99)

    def __str__(self):
        return self.title


class LabUnit(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    equipment = models.TextField()
    image = models.ImageField(default='images/placeholder.png', upload_to='images/lab')
    image2 = models.ImageField(blank=True, upload_to='images/lab')
    image3 = models.ImageField(blank=True, upload_to='images/lab')
    image4 = models.ImageField(blank=True, upload_to='images/lab')
    date_added = models.DateTimeField(default=timezone.now)
    order = models.IntegerField(default=99)

    def __str__(self):
        return self.title


class Collaborator(models.Model):
    name = models.CharField(max_length=100)
    affiliation = models.CharField(max_length=200)
    scope = models.CharField(max_length=500)
    link = models.URLField(blank=True)
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Partner(models.Model):
    name = models.CharField(max_length=100)
    scope = models.CharField(max_length=500, blank=True)
    link = models.URLField(blank=True)
    image = models.ImageField(default='images/350x200.png', upload_to='images/partners')
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Member(models.Model):
    POSITIONS = (
        ('Professor', 'Professor'),
        ('Researcher', 'Researcher'),
        ('PostDoc Researcher', 'PostDoc Researcher'),
        ('PhD Student', 'PhD Student'),
        ('Research Fellow', 'Research Fellow'),
        ('MSc Student', 'MSc Student'),
        ('Undergraduate Student', 'Undergraduate Student'),
    )
    user = models.OneToOneField(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='member')
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=50, choices=POSITIONS)
    research_area = models.CharField(max_length=200, blank=True)
    thesis = models.TextField(blank=True)
    photo = models.ImageField(default='images/profile_photos/default.jpg', upload_to='images/people', blank=True)
    alumni = models.BooleanField(default=False)
    visiting = models.BooleanField(default=False)
    highlighted = models.BooleanField(default=False)
    date_added = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(blank=True, editable=False)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.name)

        super(Member, self).save(*args, **kwargs)


class Publication(models.Model):
    PUB_TYPES = (
        ('article', 'Articles'),
        ('book-chapter', 'Book Chapter'),
        ('patent', 'Patent'),
        ('poster', 'Poster'),
        ('presentation', 'Presentation'),
        ('thesis', 'Thesis'),
    )
    THESIS_TYPES = (
        ('MSc', 'MSc Thesis'),
        ('PhD', 'PhD Thesis'),
    )
    pub_type = models.CharField(max_length=50, choices=PUB_TYPES)
    authors = models.CharField(max_length=500)
    title = models.CharField(max_length=500)
    year = models.CharField(max_length=10)
    journal = models.CharField(max_length=500, blank=True)
    volume = models.CharField(max_length=10, blank=True)
    issue = models.CharField(max_length=10, blank=True)
    pages = models.CharField(max_length=20, blank=True)
    link = models.URLField(blank=True)
    book_title = models.CharField(max_length=500, blank=True)
    publisher = models.CharField(max_length=100, blank=True)
    abstract = models.TextField(blank=True)
    patent_number = models.CharField(max_length=100, blank=True)
    conference = models.CharField(max_length=200, blank=True)
    conference_city = models.CharField(max_length=100, blank=True)
    conference_date = models.CharField(max_length=100, blank=True)
    thesis_type = models.CharField(max_length=15, choices=THESIS_TYPES, blank=True)
    thesis_coordinators = models.CharField(max_length=500, blank=True)
    thesis_institution = models.CharField(max_length=200, blank=True)
    date_added = models.DateTimeField(default=timezone.now)
    photo = models.ImageField(default='images/publications/book_placeholder.jpg', upload_to='images/publications')

    def __str__(self):
        return f'{self.pub_type} - {self.title}'


class Tool(models.Model):
    title = models.CharField(max_length=250)
    filetype = models.CharField(max_length=250, blank=True)
    description = models.TextField(blank=True)
    link = models.URLField(blank=True)
    image = models.ImageField(default='tools/tools-placeholder.png', upload_to='tools/')
    program_file = models.FileField(upload_to='tools/', blank=True)
    help_file = models.FileField(upload_to='tools/', blank=True)
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.title}'


class Award(models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=500, blank=True)
    awarded_to = models.CharField(max_length=500, blank=True)
    awarded_for = models.CharField(max_length=500, blank=True)
    link = models.URLField(blank=True)
    image = models.ImageField(default='images/awards/award-placeholder.png', upload_to='images/awards')
    date_added = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.title}'

lab/forms.py
from django import forms
from website.models import Member


class SendEmailForm(forms.Form):
    email_to = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={'checked': ''}), 
        queryset=Member.objects.filter(alumni=False).order_by('name'), 
        required=True,
    )
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

website/templates/website/awards.html
{% extends "website/base.html" %} 

{% block content %}

<div class="container mt-4">

  <h1 class="display-5 mb-3">
    {{ page_title }}
    <small class="text-muted font-weight-light d-none d-md-inline">{{ page_subtitle }}</small>
  </h1>

  {%  for award in awards  %}
  <div class="row mb-3">
    <div class="col-md-12">
      <div class="card shadow-sm mb-3 w-100">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{ award.image.url }}" class="card-img" alt="Award image">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{% if award.link %}<a class="link" href="{{ award.link }}" target="_blank">{{ award.title }}</a>{% endif %}</h5>
              {% if award.subtitle %}
              <p class="card-text">{{ award.subtitle }}</p>{% endif %} {% if award.awarded_to %}
              <p class="card-text"><strong>Awarded to:</strong> {{ award.awarded_to }}</p>{% endif %} {% if award.awarded_for %}
              <p class="card-text"><strong>Awarded for:</strong> "{{ award.awarded_for }}"</p>{% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- row closing -->
  {%  endfor %}

</div>

{% endblock content %}

website/templates/website/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Chemical Engineering Laboratory at University of Aveiro">
    <meta property="og:title" content="EgiChem" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.egichem.com" />
    <meta property="og:image" content="{% static 'website/images/logo_egichem.png' %}" />

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'website/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'website/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'website/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'website/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'website/favicon/safari-pinned-tab.svg' %}" color="#5a9c20">
    <meta name="msapplication-TileColor" content="#5a9c20">
    <meta name="theme-color" content="#ffffff">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'website/bootstrap-cosmo.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'website/main.css' %}">
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!-- Academicons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
    <!-- <link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"> -->

    <!-- Load MathJax -->
    <!-- <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script> -->
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

    <!-- Load Plotly -->
    <script src="https://cdn.plot.ly/plotly-1.58.4.min.js"></script>

    {% if page_title %}
        <title>EgiChem{% if page_title != 'Home' %} | {{ page_title }}{% endif %}</title>
    {% else %}
        <title>EgiChem</title>
    {% endif %}

    {% if not debug %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-58056773-9"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-58056773-9');
    </script>
    {% endif %}
</head>

<body>
  <!-- Header -->
  <header class="site-header bg-egichem-green">
    <div class="container px-0">
    
      <nav class="navbar navbar-expand-lg navbar-dark bg-egichem-green">
        <a class="navbar-brand my-2" href="{% url 'home' %}">
          <img src="{% static 'website/images/logo_egichem-white-notext-noshade.png' %}" style="max-height: 60px;" alt="EgiChem Logo">
          <span class="d-md-none ml-3">EgiChem Group</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'research' %}">Research</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'people' %}">People</a>
            </li>
            {% comment %} <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'lab' %}">Lab</a>
            </li> {% endcomment %}
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'publications' %}">Publications</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'partners' %}">Partners</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'blog:news' %}">News</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'tools' %}">Tools</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-item nav-link mx-2" href="{% url 'egichem' %}">
                {% if user.is_authenticated %}
                <i class="fas fa-unlock"></i>
                {% else %}
                <i class="fas fa-lock"></i>
                {% endif %}
                <span class="d-md-none ml-1">Private Area</span>
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </div>

  </header>


  <!-- Main section -->
  <main role="main">
    {% if messages %}
      {% for message in messages %}
        <div class="container mt-3">
          <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
          </div>
        </div>
      {% endfor %}
    {% endif %}
    
    <!-- Page content -->
    {% block content %}{% endblock %}
  </main>


  <!-- Footer -->
  <footer class="footer bg-egichem-footer py-4 pb-3 mt-5">
    <div class="container text-center text-md-left text-small">
      <div class="row">
        <div class="col-md-3">
          <h5 class=""><i class="fas fa-map-marker"></i> Visit</h5>
          <p class="">
            Lab 29.1.5 and Office 29.1.15<br>
            Department of Chemistry<br>
            University of Aveiro<br>
            Campus Universitário de Santiago<br>
            3810-193 Aveiro - Portugal<br>
          </p>
        </div>

        <hr class="clearfix w-75 d-md-none">

        <div class="col-md-3">
          <h5 class=""><i class="fas fa-envelope"></i> Get in touch</h5>
          <p class="">
            Email: dq-egichem[at]ua.pt<br>
            Phone: +351 234 401549<br>
            Fax: +351 234 370084<br>
          </p>
        </div>

        <hr class="clearfix w-75 d-md-none">

        <div class="col-md-3">
          <div>
            <img src="{% static 'website/images/logo_CICECO_novo.png' %}" class="img-fluid" alt="CICECO Logo">
          </div>
          <!-- <div>
            <img src="{% static 'website/images/logo_ua.png' %}" class="img-fluid" alt="">
          </div> -->
        </div>

        <hr class="clearfix w-75 d-md-none">

        <div class="col-md-3 text-md-right">
            <p class="">
              Created by:<br>
              José Aniceto
            </p>
            <p class=""><i class="far fa-copyright"></i> 
              <script>document.write(new Date().getFullYear())</script> 
              EgiChem
            </p>
        </div>

      </div>
    </div>
  </footer>

  

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
  <script src="{% static 'website/scripts.js' %}"></script>

  <script>
    $('.carousel').carousel()

    $('#collapse-button a').on('click', function(){
      $('#collapse-button').collapse('hide');
      $('#MSc_oncourse').css({'border-bottom-right-radius': '.25rem', 'border-bottom-left-radius': '.25rem'})
    });
  </script>


  <!-- how active page on navbar -->
  <script>
    const navItems = [].slice.call(
      document.querySelectorAll('.nav-item')
    ).filter(
      (node) => window.location.pathname.startsWith(node.pathname)
    );

    navItems.sort((a, b) => b.pathname.length - a.pathname.length);

    if (navItems.length) {
      navItems[0].classList.add('active');
    }
  </script>

  <!-- Page specific scripts -->
  {% block scripts %}{% endblock %}

</body>
</html>

website/templates/website/lab.html
{% extends "website/base.html" %}

{% block content %}
<div class="container mt-4">

  <h1 class="display-5 mb-3">
    {{ page_title}}
    <small class="text-muted font-weight-light d-none d-md-inline">{{ page_subtitle}}</small>
  </h1>

  {%  for unit in lab_units  %}
  <div class="row mb-3">
    <div class="col-md-12">
      <div class="card shadow-sm mb-3 w-100">
        <div class="row no-gutters">
          <div class="col-md-4">
            <!-- Image carousel -->
            <div id="units-carousel-{{ unit.pk }}" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="{{ unit.image.url }}" alt="Equipment image">
                </div>
                {% if unit.image2 %}
                <div class="carousel-item">
                  <img class="d-block w-100" src="{{ unit.image2.url }}" alt="Second equipment image">
                </div>
                {% endif %}
                {% if unit.image3 %}
                <div class="carousel-item">
                  <img class="d-block w-100" src="{{ unit.image3.url }}" alt="Third  equipment image">
                </div>
                {% endif %}
                {% if unit.image4 %}
                <div class="carousel-item">
                  <img class="d-block w-100" src="{{ unit.image4.url }}" alt="Fourth  equipment image">
                </div>
                {% endif %}
              </div>
              {% if unit.image2 %}
              <a class="carousel-control-prev" href="#units-carousel-{{ unit.pk }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#units-carousel-{{ unit.pk }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
              {% endif %}
            </div>

          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h3 class="card-title">{{ unit.title }}</h3>
              <p class="card-text">{{ unit.description }}</p>
              <p class="card-text"><small class="text-muted">{{ unit.equipment }}</small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div><!-- row closing -->
  {%  endfor %}

</div>
{% endblock content %}

website/templates/website/research.html
{% extends "website/base.html" %}

{% block content %}

<div class="container mt-4">

  <h1 class="display-5 mb-3">
    {{ page_title}}
    <small class="text-muted font-weight-light d-none d-md-inline">{{ page_subtitle}}</small>
  </h1>

  <div class="row row-cols-1 row-cols-md-3">
    {% for field in research_fields %}
    <div class="col mb-4">
      <div class="card shadow-sm h-100">
        <img src="{{ field.image.url }}" class="card-img-top" alt="{{ field.title }}">
        <div class="card-body">
          <h3 class="card-title">{{ field.title }}</h3>
          <p class="card-text">{{ field.content }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

</div>

{% endblock content %}