calculators/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.calculators_home, name='calculators_home'),
    path('carbon-dioxide/', views.carbon_dioxide, name='carbon_dioxide'),
    path('isotherms/', views.isotherms, name='isotherms'),
    path('d12-sc-co2/', views.d12_sc_co2, name='d12_sc_co2'),
    path('d12-sc-co2-old/', views.d12_sc_co2_old, name='d12_sc_co2_old'),  # to delete in future
    path('d12-polar-nonpolar/', views.d12_polar_nonpolar, name='d12_polar_nonpolar'),
    path('d12-polar-nonpolar-old/', views.d12_polar_nonpolar_old, name='d12_polar_nonpolar_old'),  # to delete in future
    path('psychrometrics/', views.psychrometrics, name='psychrometrics'),
    path('psychrometrics-vent/', views.psychrometrics_ventilation, name='psychrometrics_ventilation'),
    path('unit-conversion/', views.unit_conversion, name='unit_conversion'),
    path('air-properties/', views.air_properties, name='air_properties'),
    path('pcsaft-co2/', views.pcsaft_co2, name='pcsaft_co2'),
    path('pcsaft/', views.pcsaft, name='pcsaft'),
    path('utilities/', views.utilities, name='utilities'),
    path('d12-gas/', views.d12_gas, name='d12_gas'),
    path('d12-rg/', views.d12_rg, name='d12_rg'),
    path('klinkenberg/', views.klinkenberg, name='klinkenberg'),
    path('joback/', views.joback, name='joback'),
    path('wilke-chang/', views.wilke_chang, name='wilke_chang'),
]

egichem/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


admin.site.site_header = "EgiChem Admin"
admin.site.site_title = "EgiChem Admin Portal"
# admin.site.index_title = "Welcome to EgiChem Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('website.urls')),
    path('news/', include('blog.urls')),
    path('contact/', include('sendemail.urls')),
    path('my-egichem/', include('lab.urls')),
    path('tools/calculators/', include('calculators.urls')),
]

# Used to serve media files locally
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab/urls.py
from django.urls import path
from .views import MaterialListView, MaterialCreateView, MaterialDeleteView, MaterialUpdateView, AnnouncementListView, AnnouncementCreateView, FaqListView
from . import views


urlpatterns = [
    path('', views.egichem, name='egichem'),
    # path('inventory/', views.inventory, name='inventory'),
    path('inventory/', MaterialListView.as_view(), name='inventory'),
    path('inventory/material/new/', MaterialCreateView.as_view(), name='material-create'),
    path('inventory/material/<int:pk>/update/', MaterialUpdateView.as_view(), name='material-update'),
    path('inventory/material/<int:pk>/delete/', MaterialDeleteView.as_view(), name='material-delete'),
    path('inventory/export/', views.export, name='export'),
    path('announcements/', AnnouncementListView.as_view(), name='announcements'),
    path('announcements/new/', AnnouncementCreateView.as_view(), name='announcement-create'),
    path('announcements/<int:pk>/delete/', views.announcement_delete, name='announcement-delete'),
    path('lab-teams/', views.lab_teams, name='lab_teams'),
    path('faq/', FaqListView.as_view(), name='faqs'),
    path('contacts/', views.contacts, name='contacts'),
]

calculators/models.py
from django.db import models

# Create your models here.

calculators/forms.py
from django import forms
from properties.joback import get_group_list


class CarbonDioxideForm(forms.Form):
    COSOLVENTS = [
        ('NONE', 'No cosolvent'),
        ('ETHANOL', 'Ethanol'),
    ]
    cosolvent = forms.ChoiceField(
        choices=COSOLVENTS, 
        label="Cosolvent", 
        widget=forms.Select()
    )
    temperature = forms.FloatField(
        label='Temperature in Celsius',
        # widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    pressure = forms.FloatField(
        label='Pressure in bar'
    )
    cosolvent_fraction = forms.FloatField(
        label='Cosolvent mass fraction', 
        required=False,
        max_value=1, 
        min_value=0,
    )
    
    def clean(self):
        """Override the clean method. cosolvent_fraction is required if a cosolvent is selected."""
        cleaned_data = super().clean()
        cosolvent = cleaned_data.get('cosolvent')
        cosolvent_fraction = cleaned_data.get('cosolvent_fraction')

        if cosolvent_fraction == None:
            if cosolvent == 'NONE':
                pass
            else:
                print('raise error')
                raise forms.ValidationError('You must specify the cosolvent fraction.')


class IsothermForm(forms.Form):
    ISOTHERMS = [
        ('linear', 'Linear'),
        ('langmuir', 'Langmuir'),
        ('linearlangmuir', 'Linear-Langmuir'),
        ('bilangmuir', 'Bi-Langmuir'),
        ('freundlich', 'Freundlich'),
    ]
    isotherm_type = forms.MultipleChoiceField(
        choices=ISOTHERMS, 
        label="Isotherm type", 
        widget=forms.CheckboxSelectMultiple()
    )
    xy_data = forms.CharField(
        label='XY Data', 
        widget=forms.Textarea(attrs={'rows': 12})
    )


class PCSAFTForm(forms.Form):
    COSOLVENTS = [
        ('NONE', 'No cosolvent'),
        ('ETHANOL', 'Ethanol'),
        # ('WATER', 'Water'),
        ('METHANOL', 'Methanol'),
    ]
    cosolvent = forms.ChoiceField(
        choices=COSOLVENTS, 
        label="Cosolvent", 
        widget=forms.Select()
    )
    temperature = forms.FloatField(
        label='Temperature',
        min_value=-273.15,
        # widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    pressure = forms.FloatField(
        label='Pressure',
        min_value=0.001, 
    )
    cosolvent_fraction = forms.FloatField(
        label='Cosolvent fraction', 
        required=False,
        max_value=1, 
        min_value=0,
    )

    # Customize form widgets
    cosolvent.widget.attrs.update({'class': 'form-control'})
    temperature.widget.attrs.update({'class': 'form-control'})
    pressure.widget.attrs.update({'class': 'form-control'})
    cosolvent_fraction.widget.attrs.update({'class': 'form-control', 'step': '0.01'})

    def clean(self):
        """Override the clean method. cosolvent_fraction is required if a cosolvent is selected."""
        cleaned_data = super().clean()
        cosolvent = cleaned_data.get('cosolvent')
        cosolvent_fraction = cleaned_data.get('cosolvent_fraction')

        if cosolvent_fraction == None:
            if cosolvent == 'NONE':
                pass
            else:
                print('raise error')
                raise forms.ValidationError('You must specify the cosolvent fraction.')


class GeneralPCSAFTForm(forms.Form):
    temperature = forms.FloatField(
        label='Temperature', 
        required=False,
    )
    pressure = forms.FloatField(
        label='Pressure', 
        required=False,
        min_value=0.001, 
    )
    # Component 1
    molar_fraction_1 = forms.FloatField(
        label='Component 1 molar fraction', 
        required=False,
        max_value=1, 
        min_value=0,
    )
    molar_mass_1 = forms.FloatField(
        label='Component 1 molar mass', 
        required=False,
        min_value=0,
    )
    m_1 = forms.FloatField(
        label='Component 1 segment number', 
        required=False,
    )
    s_1 = forms.FloatField(
        label='Component 1 segment diameter', 
        required=False,
    )
    e_1 = forms.FloatField(
        label='Component 1 dispersion energy', 
        required=False,
    )
    vol_assoc_1 = forms.FloatField(
        label='Component 1 association volume',
        required=False,
    )
    e_assoc_1 = forms.FloatField(
        label='Component 1 association energy',
        required=False,
    )
    # Component 2
    molar_mass_2 = forms.FloatField(
        label='Component 1 molar mass', 
        required=False,
        min_value=0,
    )
    m_2 = forms.FloatField(
        label='Component 2 segment number', 
        required=False,
    )
    s_2 = forms.FloatField(
        label='Component 2 segment diameter', 
        required=False,
    )
    e_2 = forms.FloatField(
        label='Component 2 dispersion energy', 
        required=False,
    )
    vol_assoc_2 = forms.FloatField(
        label='Component 2 association volume',
        required=False,
    )
    e_assoc_2 = forms.FloatField(
        label='Component 2 association energy',
        required=False,
    )
    # Interaction parameters
    k_12 = forms.FloatField(
        label='Binary interaction parameters',
        required=False,
    )

    # Customize form widgets
    temperature.widget.attrs.update({'class': 'form-control'})
    pressure.widget.attrs.update({'class': 'form-control'})
    molar_fraction_1.widget.attrs.update({'class': 'form-control', 'id': 'molarFractionComponent1', 'placeholder': 'Comp 1'})
    molar_mass_1.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 1'})
    molar_mass_2.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 2'})
    m_1.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 1'})
    m_2.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 2'})
    s_1.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 1'})
    s_2.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 2'})
    e_1.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 1'})
    e_2.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 2'})
    vol_assoc_1.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 1'})
    vol_assoc_2.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 2'})
    e_assoc_1.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 1'})
    e_assoc_2.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 2'})
    k_12.widget.attrs.update({'class': 'form-control', 'placeholder': 'Comp 1 - Comp 2'})


class KlinkenbergForm(forms.Form):
    equilibrium_constant = forms.FloatField(
        label='Equilibrium constant', 
        required=True,
        min_value=0,
    )
    kinetic_constant = forms.FloatField(
        label='Kinetic constant', 
        required=True,
        min_value=0,
    )
    feed_concentration = forms.FloatField(
        label='Feed concentration', 
        required=True,
        min_value=0,
    )
    length = forms.FloatField(
        label='Column length', 
        required=True,
        min_value=0,
    )
    porosity = forms.FloatField(
        label='Bulk porosity', 
        required=True,
        min_value=0,
    )
    velocity = forms.FloatField(
        label='Interstitial velocity', 
        required=True,
        min_value=0,
    )
    time_final = forms.FloatField(
        label='Final time', 
        required=True,
        min_value=0,
    )
    xy_data = forms.CharField(
        label='Experimental data', 
        required=False,
        widget=forms.Textarea(attrs={'rows': 16})
    )
    # Customize form widgets
    equilibrium_constant.widget.attrs.update({'class': 'form-control'})
    kinetic_constant.widget.attrs.update({'class': 'form-control'})
    feed_concentration.widget.attrs.update({'class': 'form-control'})
    length.widget.attrs.update({'class': 'form-control'})
    porosity.widget.attrs.update({'class': 'form-control'})
    velocity.widget.attrs.update({'class': 'form-control'})
    time_final.widget.attrs.update({'class': 'form-control'})
    xy_data.widget.attrs.update({'class': 'form-control'})


class D12RiceGrayForm(forms.Form):
    temperature = forms.FloatField(
        label='Temperature', 
        required=False,
    )
    density = forms.FloatField(
        label='Density', 
        required=False,
        min_value=0, 
    )
    solvent_Vc = forms.FloatField(
        label='Solvent critical volume', 
        required=False,
        min_value=0,
    )
    solvent_Tc = forms.FloatField(
        label='Solvent critical temperature', 
        required=False,
        min_value=0,
    )
    solvent_M = forms.FloatField(
        label='Solvent molar mass', 
        required=False,
        min_value=0,
    )
    solute_Vc = forms.FloatField(
        label='Solute critical volume', 
        required=False,
        min_value=0,
    )
    solute_Tc = forms.FloatField(
        label='Solute critical temperature', 
        required=False,
        min_value=0,
    )
    solute_M = forms.FloatField(
        label='Solute molar mass', 
        required=False,
        min_value=0,
    )
    B_12 = forms.FloatField(
        label='Binary interaction parameter (B12)',
        required=False,
    )
    # Interaction parameters
    k_12 = forms.FloatField(
        label='Binary interaction parameter for the LJ diameter (k12)',
        required=False,
    )

    # Customize form widgets
    temperature.widget.attrs.update({'class': 'form-control'})
    density.widget.attrs.update({'class': 'form-control'})
    solvent_Vc.widget.attrs.update({'class': 'form-control'})
    solvent_Tc.widget.attrs.update({'class': 'form-control'})
    solvent_M.widget.attrs.update({'class': 'form-control'})
    solute_Vc.widget.attrs.update({'class': 'form-control'})
    solute_Tc.widget.attrs.update({'class': 'form-control'})
    solute_M.widget.attrs.update({'class': 'form-control'})

calculators/templates/calculators/calculators_home.html
{% extends "website/base.html" %}

{% block content %}

<div class="container mt-4">
  {% include 'calculators/_includes/calculators.html' %}
</div>

{% endblock %}

calculators/templates/calculators/d12-rg.html
{% extends "website/base.html" %} 
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-4">

  <div class="row mb-3">
    <div class="col">
      <h1>Diffusion coefficients calculation using Rice and Gray model</h1>
      <p class="lead">Calculates the tracer diffusion coefficients of a given solute in a solvent using the Rice and Gray model.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">

      <form method="POST">
        {% csrf_token %}

        <div class="form-group row my-1">

          <label for="id_temperature" class="col-sm-5 col-form-label">{{ form.temperature.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.temperature }}
              <!-- <input id="temperature" type="number" step="any" class="form-control" aria-label="Temperature" aria-describedby="addon-temperature"> -->
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_temperature">K</span>
              </div>
            </div>
          </div>
          {{ form.temperature.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_density" class="col-sm-5 col-form-label">{{ form.density.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.density }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_density">g cm<sup>-3</sup></span>
              </div>
            </div>
          </div>
          {{ form.density.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_solvent_Vc" class="col-sm-5 col-form-label">{{ form.solvent_Vc.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.solvent_Vc }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_solvent_Vc">cm<sup>3</sup> mol<sup>-1</sup></span>
              </div>
            </div>
          </div>
          {{ form.solvent_Vc.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_solvent_Tc" class="col-sm-5 col-form-label">{{ form.solvent_Tc.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.solvent_Tc }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_solvent_Tc">K</span>
              </div>
            </div>
          </div>
          {{ form.solvent_Tc.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_solvent_M" class="col-sm-5 col-form-label">{{ form.solvent_M.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.solvent_M }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_solvent_M">g mol<sup>-1</sup></span>
              </div>
            </div>
          </div>
          {{ form.solvent_M.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_solute_Vc" class="col-sm-5 col-form-label">{{ form.solute_Vc.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.solute_Vc }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_solute_Vc">cm<sup>3</sup> mol<sup>-1</sup></span>
              </div>
            </div>
          </div>
          {{ form.solute_Vc.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_solute_Tc" class="col-sm-5 col-form-label">{{ form.solute_Tc.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.solute_Tc }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_solute_Tc">K</span>
              </div>
            </div>
          </div>
          {{ form.solute_Tc.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_solute_M" class="col-sm-5 col-form-label">{{ form.solute_M.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.solute_M }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_solute_M">g mol<sup>-1</sup></span>
              </div>
            </div>
          </div>
          {{ form.solute_M.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_B_12" class="col-sm-5 col-form-label">{{ form.B_12.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.B_12 }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_B_12">-</span>
              </div>
            </div>
          </div>
          {{ form.B_12.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_k_12" class="col-sm-5 col-form-label">{{ form.k_12.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.k_12 }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_k_12">-</span>
              </div>
            </div>
          </div>
          {{ form.k_12.errors }}
        </div>
        
        <button type="submit" class="btn btn-egichem">Calculate</button>
        <!-- <a href="{% url 'pcsaft' %}" type="button" class="btn btn-outline-egichem">Reset</a> -->
      </form>

    </div>

    <div class="col-md-5 offset-md-1 mt-3 mt-md-0">
      <form>
        
        <div class="form-group row">

          <label for="d12-result" class="col-sm-6 col-form-label">Diffusion coefficient</label>
          <div class="col-sm-6">
            <div class="input-group mb-3">
              <input value="{{ d12_result }}" id="d12-result" class="form-control" aria-label="Diffusion coefficient" aria-describedby="addon-d12-result" readonly>
              <div class="input-group-append">
                <span class="input-group-text" id="addon-d12-result">cm<sup>2</sup> s<sup>-1</sup></span>
              </div>
            </div>
          </div>

        </div>

      </form>
    </div>
  </div>


  <div class="row mt-4">
    <div class="col">

      <h4>Notes</h4>
      <p>This calculator the Rice and Gray model to estimate the diffusion coefficients of solute in a solvent.</p>
      <!-- <p>Data for known systems can be found in xxx</p> -->

      <h4>References</h4>
      <p><a href="https://doi.org/10.3390/ma15186416">B. Zêzere, I. Portugal, J.R.B. Gomes, C.M. Silva. Modeling tracer diffusion coefficients of any type of solutes in polar and non-polar dense solvents, Materials 15 (2022) 6416.</a></p>

    </div>
  </div>

</div>
{% endblock content %} 

calculators/templates/calculators/d12_sc_co2.html
{% extends "website/base.html" %} 
{% load static %}
{% block content %}

<div class="container mt-4">

  <div class="row mb-3">
    <div class="col">
      <h1 class="display-5 mb-3">Estimation of diffusivities in supercritical carbon dioxide</h1>
      <p class="lead">Calculates the diffusion coefficients of a solute in supercritical carbon dioxide using the Machine Learning model proposed in <a href="https://www.sciencedirect.com/science/article/pii/S0167732221000076">Aniceto et al., 2021</a>.</p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-6">

      <form method="POST">
        {% csrf_token %}

        <div class="form-group row my-1">
          <label for="id_temperature" class="col-sm-5 col-form-label">{{ form.temperature.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.temperature }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_temperature">K</span>
              </div>
            </div>
          </div>
          {{ form.temperature.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_density" class="col-sm-5 col-form-label">{{ form.density.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.density }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_density">g cm<sup>-3</sup></span>
              </div>
            </div>
          </div>
          {{ form.density.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_molarmass" class="col-sm-5 col-form-label">{{ form.molarmass.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.molarmass }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_molarmass">g mol<sup>-1</sup></span>
              </div>
            </div>
          </div>
          {{ form.molarmass.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_criticalpressure" class="col-sm-5 col-form-label">{{ form.criticalpressure.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.criticalpressure }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_criticalpressure">bar</span>
              </div>
            </div>
          </div>
          {{ form.criticalpressure.errors }}
        </div>

        <div class="form-group row my-1">
          <label for="id_acentricfactor" class="col-sm-5 col-form-label">{{ form.acentricfactor.label }}</label>
          <div class="col-sm-7">
            <div class="input-group mb-3">
              {{ form.acentricfactor }}
              <div class="input-group-append">
                <span class="input-group-text" id="addon-id_acentricfactor">-</span>
              </div>
            </div>
          </div>
          {{ form.acentricfactor.errors }}
        </div>

        <button type="submit" class="btn btn-egichem">Calculate</button>
      </form>

    </div>

    <div class="col-md-5 offset-md-1 mt-3 mt-md-0">
      <form>
        
        <div class="form-group row">

          <label for="d12-result" class="col-sm-6 col-form-label">Diffusion coefficient</label>
          <div class="col-sm-6">
            <div class="input-group mb-3">
              <input value="{{ d12_result }}" id="d12-result" class="form-control" aria-label="Diffusion coefficient" aria-describedby="addon-d12-result" readonly>
              <div class="input-group-append">
                <span class="input-group-text" id="addon-d12-result">cm<sup>2</sup> s<sup>-1</sup></span>
              </div>
            </div>
          </div>

        </div>

      </form>
    </div>
  </div>

  <div class="alert alert-secondary mt-4">
    <div class="row">
      <div class="col-lg-8 align-self-center">
        <span>You can download the software with this calculator for offline use.</span>
      </div>
      <div class="col-lg-4">
        <div class="float-md-right mt-2 mt-md-0">
          <a href="{% static 'calculators/ml-d12.zip' %}" class="btn btn-egichem" download>Download</a>
          <a href="https://github.com/EgiChem/ml-D12-app" class="btn btn-egichem" target="_blank">Github</a>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col">
      <h4>Notes</h4>
      <p>This tool estimates the binary diffusivity of a solute in supercritical carbon dioxide using a machine learning model trained with 4000 experimental data points from over 170 systems. For more information, check the paper below.</p>
      
      <h4>Citing</h4>
      <p>If you use this calculator for a scientific publication, please cite:</p>
      <p><a href="https://www.sciencedirect.com/science/article/pii/S0167732221000076">J.P.S. Aniceto, B. Zêzere, C.M. Silva. Machine learning models for the prediction of diffusivities in supercritical CO2 systems, Journal of Molecular Liquids (2021) 115281.</a></p>
      
      <!-- <h4>References</h4>
      <p>J.P.S. Aniceto, B. Zêzere, C.M. Silva. Machine learning models for the prediction of diffusivities in supercritical CO2 systems, Journal of Molecular Liquids (2021) 115281.</p> -->
    </div>
  </div>

</div>
{% endblock content %}